### PR TITLE
columType is deprecated

### PR DESCRIPTION
**Pull request by tgoeminne**
some of the function is raising deprecated errors.

### CODE REVIEW

**Comment by lilHermit** [comment]
Hi thank-you for taking the time to submit this PR, sorry it's taken so long to get back to you. 

We might need a version check/if so we don't break backwards compatibility. Perhaps a wrapper method?

**Comment by lilHermit** [comment]
@tgoeminne  Can you test master to see if that commit fixes your issue? I'll push 4003 soon.

**Comment by johnneijzen** [comment]
this broke cakephp 3.7 bake for me
i think this is because of
columns() - Get the column names in the table.
and getColumn() - Get column data in the table.

**Comment by lilHermit** [comment]
@johnneijzen if you want to test `dev-master` this should be fix, I'll push a full release shortly. once we are happy

**Pull request closed without merging**
