### PR TITLE
fixes for cakephp 3.7 compatibility

### PR DESCRIPTION
**Pull request by Ali1**

### CODE REVIEW

**Comment by lilHermit** [comment]
I believe I fixed this but haven't pushed the changes. I will check tomorrow and push so you can test it using `master`

**Comment by Ali1** [comment]
1 of the issues has been fixed on mater -thx

**Comment by lilHermit** [comment]
> 1 of the issues has been fixed on master -thx

Hi, which issue isn't fixed in master? 

1) Missing required should be fixed in 81ac1ec4a41766ec129ec6e0fc5268a39ca5edac
2) confirmJs should be fixed by changing the way the templates are merged in 1eb6d806a6e487dab28402ce446fd207e38267c4

Thanks again for your time reporting these issues

**Comment by Ali1** [comment]
Aha didn't realise the second one. I'll try it later and re-open if any issues. Thanks for updating!

**Pull request closed without merging**
